{% set name = "google-cloud-cpp" %}
{% set version = "2.9.1" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/googleapis/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: e63d49799eadca7f27c1d7192668ee7cc7fa7dad478c03868d1ce54d662d6ea9
  patches:
    # Several libraries do not compile under Conda.  Depending on the platform
    # and compiler, they need a newer version of Protobuf.  That is, they
    # compile with older versions of Protobuf on some combinations of platform,
    # combpiler, and C++ standard library. For more information, see:
    #   https://github.com/googleapis/google-cloud-cpp/issues/8125
    #   https://github.com/googleapis/google-cloud-cpp/issues/8145
    #   https://github.com/googleapis/google-cloud-cpp/issues/8785
    - 0001-disable-libraries.patch

build:
  number: 0
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - libgrpc
    - libprotobuf
  host:
    - libabseil
    - libcrc32c
    - libcurl
    - libgrpc
    - libprotobuf
    - openssl
    - nlohmann_json
    - zlib

outputs:
  - name: libgoogle-cloud
    script: build-libgoogle-cloud.sh  # [not win]
    script: build-libgoogle-cloud.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage("libgoogle-cloud", max_pin="x.x.x") }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja
        - libgrpc
        - libprotobuf
      host:
        - libabseil
        - libcrc32c
        - libcurl
        - libgrpc
        - libprotobuf
        - openssl
        - nlohmann_json
      run_constrained:
        - google-cloud-cpp {{ version }} *_{{ PKG_BUILDNUM }}
    test:
      commands:
        - test -f $PREFIX/lib/libgoogle_cloud_cpp_storage.{{ version }}.dylib  # [osx]
        - test -f $PREFIX/lib/libgoogle_cloud_cpp_storage.so.{{ version }}  # [linux]
        - test ! -f $PREFIX/lib/pkgconfig/google_cloud_cpp_storage.pc  # [not win]
        - test ! -f $PREFIX/lib/cmake/google_cloud_cpp_storage/google_cloud_cpp_storage-config.cmake  # [not win]
        - test ! -f $PREFIX/include/google/cloud/storage/version.h  # [not win]
        - test -f $PREFIX/lib/libgoogle_cloud_cpp_bigtable.{{ version }}.dylib  # [osx]
        - test -f $PREFIX/lib/libgoogle_cloud_cpp_bigtable.so.{{ version }}  # [linux]
        - test ! -f $PREFIX/lib/cmake/google_cloud_cpp_bigtable/google_cloud_cpp_bigtable-config.cmake  # [not win]
        - test ! -f $PREFIX/include/google/cloud/bigtable/version.h  # [not win]
        # Currently, the windows build is static.
        #- if not exist %LIBRARY_PREFIX%\\bin\\libgoogle_cloud_cpp_storage.dll exit 1  # [win]
        #- if not exist %LIBRARY_PREFIX%\\lib\\pkgconfig\\google_cloud_cpp_storage.pc exit 1  # [win]
        - if exist %LIBRARY_PREFIX%\\lib\\cmake\\google_cloud_cpp_storage\\google_cloud_cpp_storage-config.cmake exit 1  # [win]
        - if exist %LIBRARY_PREFIX%\\include\\google\\cloud\\storage\\version.h exit 1  # [win]
        #- if not exist %LIBRARY_PREFIX%\\bin\\libgoogle_cloud_cpp_bigtable.dll exit 1  # [win]
        - if exist %LIBRARY_PREFIX%\\lib\\cmake\\google_cloud_cpp_bigtable\\google_cloud_cpp_bigtable-config.cmake exit 1  # [win]
        - if exist %LIBRARY_PREFIX%\\include\\google\\cloud\\bigtable\\version.h exit 1  # [win]
  - name: google-cloud-cpp
    script: build-libgoogle-cloud.sh  # [not win]
    script: build-libgoogle-cloud.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage("libgoogle-cloud", max_pin="x.x.x") }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja
        - libgrpc
        - libprotobuf
      host:
        - {{ pin_subpackage("libgoogle-cloud", exact=True) }}
        - libabseil
        - libcrc32c
        - libcurl
        - libgrpc
        - libprotobuf
        - openssl
        - nlohmann_json
      run:
        - {{ pin_subpackage("libgoogle-cloud", exact=True) }}
        - nlohmann_json
        # cannot load package without zlib because it's specified
        # as required; if possible, this should be removed upstream
        - zlib
    test:
      commands:
        - ./run_test_google_cloud_cpp.sh  # [not win]
        - ./run_test_google_cloud_cpp.bat  # [win]
        - test -f $PREFIX/lib/cmake/google_cloud_cpp_storage/google_cloud_cpp_storage-config.cmake  # [not win]
        - test -f $PREFIX/include/google/cloud/storage/version.h  # [not win]
        - test -f $PREFIX/lib/cmake/google_cloud_cpp_bigtable/google_cloud_cpp_bigtable-config.cmake  # [not win]
        - test -f $PREFIX/include/google/cloud/bigtable/version.h  # [not win]
        - if not exist %LIBRARY_PREFIX%\\lib\\cmake\\google_cloud_cpp_storage\\google_cloud_cpp_storage-config.cmake exit 1  # [win]
        - if not exist %LIBRARY_PREFIX%\\include\\google\\cloud\\storage\\version.h exit 1  # [win]
        - if not exist %LIBRARY_PREFIX%\\lib\\cmake\\google_cloud_cpp_bigtable\\google_cloud_cpp_bigtable-config.cmake exit 1  # [win]
        - if not exist %LIBRARY_PREFIX%\\include\\google\\cloud\\bigtable\\version.h exit 1  # [win]
      requires:
        - {{ compiler('cxx') }}
        - cmake
        - ninja
      files:
        - run_test_google_cloud_cpp.sh
        - run_test_google_cloud_cpp.bat
      source_files:
        - google/cloud/storage/quickstart/*.cc
        - google/cloud/storage/quickstart/CMakeLists.txt

about:
  home: https://github.com/googleapis/google-cloud-cpp
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google Cloud Client Library for C++

extra:
  feedstock-name: google-cloud-cpp
  recipe-maintainers:
    - coryan
    - davidbrochart
    - xhochy
    - h-vetinari
