{% set name = "google-cloud-cpp" %}
{% set version = "1.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/googleapis/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 14bf9bf97431b890e0ae5dca8f8904841d4883b8596a7108a42f5700ae58d711

build:
  number: 1
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("google-cloud-cpp", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - c-ares
    - libcrc32c
    - googleapis-cpp
    - grpc-cpp
    - libcurl
    - libprotobuf
    - openssl
    - nlohmann_json
  run:

test:
  commands:
    - test -f $PREFIX/lib/libstorage_client${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/cmake/storage_client/storage-targets.cmake  # [unix]
    - test -f $PREFIX/include/google/cloud/storage/version.h  # [unix]
    - test -f $PREFIX/lib/libbigtable_client${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/cmake/bigtable_client/bigtable-targets.cmake  # [unix]
    - test -f $PREFIX/include/google/cloud/bigtable/version.h  # [unix]
    - test -f $PREFIX/lib/libfirestore_client${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/cmake/firestore_client/firestore-targets.cmake  # [unix]
    - test -f $PREFIX/include/google/cloud/firestore/field_path.h  # [unix]

about:
  home: https://github.com/googleapis/google-cloud-cpp
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google Cloud Client Library for C++

extra:
  recipe-maintainers:
    - xhochy
    - davidbrochart
