{% set name = "google-cloud-cpp" %}
{% set version = "1.32.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/googleapis/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: c62338389f76915179fe61d8c0f5fefa06131b4e0d7312707af5309b1394e099

build:
  number: 1
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("google-cloud-cpp", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - grpc-cpp
    - libprotobuf
  host:
    - abseil-cpp
    - libcrc32c
    - grpc-cpp
    - libcurl
    - libprotobuf
    - openssl
    - nlohmann_json
  run:

test:
  commands:
    - test -f $PREFIX/lib/libgoogle_cloud_cpp_storage${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/pkgconfig/google_cloud_cpp_storage.pc  # [unix]
    - test -f $PREFIX/lib/cmake/google_cloud_cpp_storage/google_cloud_cpp_storage-config.cmake  # [unix]
    - test -f $PREFIX/include/google/cloud/storage/version.h  # [unix]
    - test -f $PREFIX/lib/libgoogle_cloud_cpp_bigtable${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/cmake/google_cloud_cpp_bigtable/google_cloud_cpp_bigtable-config.cmake  # [unix]
    - test -f $PREFIX/include/google/cloud/bigtable/version.h  # [unix]
    - test -f $PREFIX/lib/libgoogle_cloud_cpp_firestore${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/cmake/google_cloud_cpp_firestore/google_cloud_cpp_firestore-config.cmake  # [unix]
    - test -f $PREFIX/include/google/cloud/firestore/field_path.h  # [unix]

about:
  home: https://github.com/googleapis/google-cloud-cpp
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google Cloud Client Library for C++

extra:
  recipe-maintainers:
    - xhochy
    - davidbrochart
