azure:
  settings_win:
    variables:
      CONDA_BLD_PATH: C:\\bld\\
bot:
  automerge: true
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
remote_ci_setup:
 - conda-forge-ci-setup=4
 - conda-build>=24.1
 - py-lief<0.14
test: native_and_emulated
